name: Windows RDP (LocalTunnel - FREE)

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration in hours (max 6)'
        required: false
        default: '6'
        type: string
      password:
        description: 'Custom RDP password (optional)'
        required: false
        type: string

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 hours max

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Enable RDP
      run: |
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -value 1
        
        # Set password for runneradmin user
        $password = "${{ github.event.inputs.password }}"
        if ([string]::IsNullOrEmpty($password)) {
          $password = "${{ secrets.RDP_PASSWORD }}"
        }
        if ([string]::IsNullOrEmpty($password)) {
          $password = "P@ssw0rd123!"
        }
        
        net user runneradmin $password
        net localgroup "Remote Desktop Users" runneradmin /add
        
        Write-Host "RDP enabled successfully!"
        Write-Host "Username: runneradmin"
        Write-Host "Password: $password"

    - name: Install Node.js and LocalTunnel
      run: |
        # Install Node.js (already available in GitHub Actions)
        Write-Host "📦 Installing LocalTunnel..."
        npm install -g localtunnel
        
        # Verify installation
        npx lt --version

    - name: Install Essential Software
      run: |
        # Install Chocolatey first
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        
        # Install software
        choco install -y googlechrome
        choco install -y firefox
        choco install -y 7zip
        choco install -y notepadplusplus
        choco install -y git
        choco install -y python
        choco install -y vscode
        choco install -y putty
        choco install -y winscp

    - name: Setup LocalTunnel for RDP
      run: |
        Write-Host "🚀 Starting LocalTunnel for RDP..."
        
        # Generate random subdomain
        $subdomain = "rdp-$(Get-Random -Minimum 1000 -Maximum 9999)"
        
        # Start localtunnel in background
        Start-Process -FilePath "npx" -ArgumentList "lt", "--port", "3389", "--subdomain", $subdomain -WindowStyle Hidden -RedirectStandardOutput "tunnel.log" -RedirectStandardError "tunnel_error.log"
        
        # Wait for tunnel to start
        Write-Host "⏳ Waiting for LocalTunnel to initialize..."
        Start-Sleep -Seconds 10
        
        # Check if process is running
        $tunnelProcess = Get-Process -Name "node" -ErrorAction SilentlyContinue | Where-Object { $_.ProcessName -eq "node" }
        if ($tunnelProcess) {
          Write-Host "✅ LocalTunnel started successfully"
        } else {
          Write-Host "❌ LocalTunnel failed to start"
          if (Test-Path "tunnel_error.log") {
            Write-Host "📋 Error logs:"
            Get-Content "tunnel_error.log"
          }
        }

    - name: Get Tunnel Connection Info
      run: |
        $maxAttempts = 15
        $attempt = 1
        $tunnelFound = $false
        
        Write-Host "🔍 Looking for LocalTunnel connection info..."
        
        while ($attempt -le $maxAttempts -and -not $tunnelFound) {
          Write-Host "Attempt $attempt/$maxAttempts - Checking tunnel logs..."
          
          if (Test-Path "tunnel.log") {
            $logContent = Get-Content "tunnel.log" -Raw
            
            # Look for tunnel URL in logs
            if ($logContent -match "https://[a-zA-Z0-9-]+\.loca\.lt") {
              $tunnelUrl = $matches[0]
              
              Write-Host "=================================="
              Write-Host "🎉 RDP TUNNEL IS READY!"
              Write-Host "=================================="
              Write-Host "Tunnel URL: $tunnelUrl"
              Write-Host "Protocol: TCP over HTTPS tunnel"
              Write-Host "Username: runneradmin"
              Write-Host "Password: $(if ('${{ github.event.inputs.password }}') { '${{ github.event.inputs.password }}' } elseif ('${{ secrets.RDP_PASSWORD }}') { '${{ secrets.RDP_PASSWORD }}' } else { 'P@ssw0rd123!' })"
              Write-Host "=================================="
              Write-Host ""
              Write-Host "📋 Connection Instructions:"
              Write-Host "1. This creates an HTTPS tunnel to RDP"
              Write-Host "2. You'll need a TCP-over-HTTPS client"
              Write-Host "3. Or use SSH port forwarding"
              Write-Host "4. Advanced users can setup proxy connection"
              Write-Host ""
              Write-Host "🌐 Web Interface:"
              Write-Host "Visit: $tunnelUrl"
              Write-Host ""
              Write-Host "⏰ Session will last for ${{ github.event.inputs.duration || '6' }} hours"
              Write-Host "=================================="
              $tunnelFound = $true
            } else {
              Write-Host "⏳ Tunnel URL not found yet, waiting..."
            }
          } else {
            Write-Host "⏳ Tunnel log file not created yet..."
          }
          
          if (-not $tunnelFound) {
            Start-Sleep -Seconds 8
            $attempt++
          }
        }
        
        if (-not $tunnelFound) {
          Write-Host "❌ Could not find tunnel URL after $maxAttempts attempts"
          Write-Host "📋 Available log content:"
          if (Test-Path "tunnel.log") {
            Get-Content "tunnel.log"
          }
          
          # Try alternative approach - direct lt command
          Write-Host "🔄 Trying alternative approach..."
          $subdomain2 = "rdp-$(Get-Random -Minimum 1000 -Maximum 9999)"
          npx lt --port 3389 --subdomain $subdomain2
        }

    - name: Keep session alive
      run: |
        $duration = [int]"${{ github.event.inputs.duration || '6' }}"
        $endTime = (Get-Date).AddHours($duration)
        
        Write-Host "🔄 Keeping session alive until $(Get-Date $endTime -Format 'yyyy-MM-dd HH:mm:ss')"
        
        while ((Get-Date) -lt $endTime) {
          Write-Host "⏰ Session active - $(Get-Date -Format 'HH:mm:ss') - Remaining: $([math]::Round(($endTime - (Get-Date)).TotalMinutes, 1)) minutes"
          
          # Check if tunnel is still running
          $tunnelProcess = Get-Process -Name "node" -ErrorAction SilentlyContinue | Where-Object { $_.ProcessName -eq "node" }
          if (-not $tunnelProcess) {
            Write-Host "⚠️ LocalTunnel died, restarting..."
            $subdomain = "rdp-$(Get-Random -Minimum 1000 -Maximum 9999)"
            Start-Process -FilePath "npx" -ArgumentList "lt", "--port", "3389", "--subdomain", $subdomain -WindowStyle Hidden -RedirectStandardOutput "tunnel.log" -RedirectStandardError "tunnel_error.log"
            Start-Sleep -Seconds 10
          }
          
          # Keep system active
          Add-Type -AssemblyName System.Windows.Forms
          [System.Windows.Forms.SendKeys]::SendWait("{SCROLLLOCK}")
          
          Start-Sleep -Seconds 300  # Wait 5 minutes
        }
        
        Write-Host "⏰ Session time expired. Shutting down..."

    - name: Cleanup
      if: always()
      run: |
        Write-Host "🧹 Cleaning up..."
        Get-Process -Name "node" -ErrorAction SilentlyContinue | Where-Object { $_.ProcessName -eq "node" } | Stop-Process -Force
        Write-Host "✅ Cleanup completed"
